### PR TITLE
OpenVX - gpu_buffer_offset fix

### LINKED ISSUE #1452: [Issue]: OpenVX - Canny Test Failure
### Problem Description

Canny kernels getting memory access fault in GFX942

### Operating System

Ubuntu

### CPU

All

### GPU

AMD Instinct MI300

### Other

_No response_

### ROCm Version

ROCm 6.0.0

### ROCm Component

MIVisionX

### Steps to Reproduce

_No response_

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hansely**
This PR removes `gpu_buffer_offset` being updated during the merge process.
It will make sure the `goffset `doesn't try to access offset value that are out of bounds while leveraging buffer reuse for memory optimization.

Fixes #1452

### CODE REVIEW

File: amd_openvx/openvx/hipvx/vision_kernels.cpp [hunk 1]
```diff
@@ -42,9 +42,7 @@ Hip_CannySobel_U16_U8_3x3_L1NORM(uint dstWidth, uint dstHeight,
     { // load 136x18 bytes into local memory using 16x16 workgroup
         int loffset = ly * 136 + (lx << 3);
         int goffset = (y - 1) * srcImageStrideInBytes + x - 4;
-        if (goffset >= 0) {
-            *((uint2 *)(&lbuf[loffset])) = *((uint2 *)(&pSrcImage[goffset]));
-        }
+        *((uint2 *)(&lbuf[loffset])) = *((uint2 *)(&pSrcImage[goffset]));
```
Comment (rrawther) [inline amd_openvx/openvx/hipvx/vision_kernels.cpp:45]: please use static_cast<>() for casting

File: amd_openvx/openvx/hipvx/vision_kernels.cpp [hunk 2]
```diff
@@ -57,7 +55,7 @@ Hip_CannySobel_U16_U8_3x3_L1NORM(uint dstWidth, uint dstHeight,
             goffset = (y - ly + id - 1) * srcImageStrideInBytes + (((x >> 3) - lx) << 3) + 124;
             doExtraLoad = (id < 18) ? true : false;
         }
-        if (doExtraLoad && goffset >= 0) {
+        if (doExtraLoad) {
             *((uint2 *)(&lbuf[loffset])) = *((uint2 *)(&pSrcImage[goffset]));
```
Comment (rrawther) [inline amd_openvx/openvx/hipvx/vision_kernels.cpp:59]: please use static_cast<>() for casting

**Review by rrawther — APPROVED** [review]

**Review by kiritigowda — APPROVED** [review]
